const menuBar = document.getElementById("menu-bar");
const navMenu = document.getElementById("nav-menu");
const closeButton = document.getElementById("btn-close");

menuBar.onclick = function handleMenuBar(e) {
    e.preventDefault();
    navMenu.classList.remove("nav-menu");
    navMenu.classList.add("nav-menu");
    navMenu.classList.add("active");
}

closeButton.onclick = function handleCloseButton(e) {
    e.preventDefault();
    navMenu.classList.remove("active");
}

document.addEventListener("contextmenu", event => {
    event.preventDefault();
})

var array = [
    "100 sec left",
    "99 sec left",
    "98 sec left",
    "97 sec left",
    "96 sec left",
    "95 sec left",
    "94 sec left",
    "93 sec left",
    "92 sec left",
    "91 sec left",
    "90 sec left",
    "89 sec left",
    "88 sec left",
    "87 sec left",
    "86 sec left",
    "85 sec left",
    "84 sec left",
    "83 sec left",
    "82 sec left",
    "81 sec left",
    "80 sec left",
    "79 sec left",
    "78 sec left",
    "77 sec left",
    "76 sec left",
    "75 sec left",
    "74 sec left",
    "73 sec left",
    "72 sec left",
    "71 sec left",
    "70 sec left",
    "69 sec left",
    "68 sec left",
    "67 sec left",
    "66 sec left",
    "65 sec left",
    "64 sec left",
    "63 sec left",
    "62 sec left",
    "61 sec left",
    "60 sec left",
    "59 sec left",
    "58 sec left",
    "57 sec left",
    "56 sec left",
    "55 sec left",
    "54 sec left",
    "53 sec left",
    "52 sec left",
    "51 sec left",
    "50 sec left",
    "49 sec left",
    "48 sec left",
    "47 sec left",
    "46 sec left",
    "45 sec left",
    "44 sec left",
    "43 sec left",
    "42 sec left",
    "41 sec left",
    "40 sec left",
    "39 sec left",
    "38 sec left",
    "37 sec left",
    "36 sec left",
    "35 sec left",
    "34 sec left",
    "33 sec left",
    "32 sec left",
    "31 sec left",
    "30 sec left",
    "29 sec left",
    "28 sec left",
    "27 sec left",
    "26 sec left",
    "25 sec left",
    "24 sec left",
    "23 sec left",
    "22 sec left",
    "21 sec left",
    "20 sec left",
    "19 sec left",
    "18 sec left",
    "17 sec left",
    "16 sec left",
    "15 sec left",
    "14 sec left",
    "13 sec left",
    "12 sec left",
    "11 sec left",
    "10 sec left",
    "9 sec left",
    "8 sec left",
    "7 sec left",
    "6 sec left",
    "5 sec left",
    "4 sec left",
    "3 sec left",
    "2 sec left",
    "1 sec left",
    "https://mrperfectgaurav.github.io/frontend-challenge/"
]